name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync with upstream
        run: |
          git config --global user.name joshuaboys
          git config --global user.email josh@arkahna.io
          git remote add upstream https://github.com/microsoft/magentic-ui
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}